compose-build:
	docker-compose build

compose-up:
	docker-compose up

compose-ps:
	docker-compose ps

compose-stop:
	docker-compose stop

compose-down:
	docker-compose down

build:
	docker build .

push:

tag:
